<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>azure, azure-function, python, asyncio on by Alex Code blog</title><link>https://byalexblog.net/tags/azure-azure-function-python-asyncio/</link><description>Recent content in azure, azure-function, python, asyncio on by Alex Code blog</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Sat, 10 Feb 2024 10:03:16 +0000</lastBuildDate><atom:link href="https://byalexblog.net/tags/azure-azure-function-python-asyncio/index.xml" rel="self" type="application/rss+xml"/><item><title>Azure Function Encountered an Error ServiceUnavailable From Host Runtime</title><link>https://byalexblog.net/article/azure-function-encountered-an-error-serviceunavailable-from-host-runtime/</link><pubDate>Sat, 10 Feb 2024 10:03:16 +0000</pubDate><guid>https://byalexblog.net/article/azure-function-encountered-an-error-serviceunavailable-from-host-runtime/</guid><description>&lt;p>&lt;img src="https://byalexblog.net/images/azure-function-encountered-an-error-serviceunavailable-from-host-runtime/logo.webp" alt="">
I recently had an issue deploying Python 3.10 Azure Function on App Service Plan. The error message was:&lt;/p>
&lt;pre tabindex="0">&lt;code>9:38:43 AM myfunc: Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
9:38:56 AM myfunc: Syncing triggers...
9:39:50 AM myfunc: Syncing triggers (Attempt 2/6)...
9:40:51 AM myfunc: Syncing triggers (Attempt 3/6)...
9:42:01 AM myfunc: Syncing triggers (Attempt 4/6)...
9:43:01 AM myfunc: Syncing triggers (Attempt 5/6)...
9:45:12 AM myfunc: Syncing triggers (Attempt 6/6)...
9:45:33 AM: Error: Encountered an error (ServiceUnavailable) from host runtime.
&lt;/code>&lt;/pre>&lt;p>Here is my investigation and solution.&lt;/p></description></item></channel></rss>